brazilian_market:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'dataeng') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'dataeng123') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'brazilian_market') }}"
      schema: analytics
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      search_path: "raw,staging,analytics,public"

    prod:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      port: "{{ env_var('POSTGRES_PORT') | int }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: analytics
      threads: 8
      keepalives_idle: 0
      connect_timeout: 10
